# Generated by Django 3.1.1 on 2020-09-21 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('building', models.CharField(choices=[('SY', '상허연구관'), ('JG', '종합강의동'), ('SG', '생명과학관'), ('DS', '동물생명과학관'), ('SH', '산학협동관'), ('SC', '새천년관'), ('UG', '의생명과학연구관'), ('GG', '교육과학관'), ('YM', '예술문화관'), ('HB', '해봉부동산학관'), ('GC', '건축관'), ('IM', '인문학관'), ('GY', '경영관'), ('CU', '창의관'), ('GH', '과학관'), ('ENG', '공학관')], max_length=10)),
                ('professor', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LectureTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_of_the_week', models.CharField(choices=[('MON', '월'), ('TUE', '화'), ('WED', '수'), ('THR', '목'), ('FRI', '금'), ('SAT', '토'), ('SUN', '일')], max_length=3)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_times', to='time_table.lecture')),
            ],
        ),
    ]
