# Generated by Django 3.1.1 on 2020-09-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0002_auto_20200922_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='building',
            field=models.CharField(choices=[('상허연구관', '상허관'), ('종합강의동', '종강'), ('경영관', '경영'), ('산학협동관', '산학'), ('신공학관', '신공'), ('생명과학관', '생'), ('동물생명과학관', '동'), ('새천년관', '새'), ('의생명과학연구관', '수'), ('교육과학관', '사'), ('예술문화관', '예'), ('해봉부동산학관', '부'), ('건축관', '건'), ('인문학관', '문'), ('창의관', '창'), ('과학관', '이'), ('공학관', '공')], default='건물이름', max_length=10),
        ),
    ]
