# Generated by Django 3.1.1 on 2020-09-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0003_lecture_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturetime',
            name='building',
        ),
        migrations.AddField(
            model_name='lecturetime',
            name='floor',
            field=models.CharField(default='엌ㅋ', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='building',
            field=models.CharField(default='건물이름', max_length=10),
        ),
    ]
