# Generated by Django 3.1.1 on 2020-12-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0005_auto_20201121_1142'),
        ('time_table', '0005_auto_20201102_2027'),
    ]

    operations = [
    ]
